---
title: "Credit Fraud"
author: "Nathan Hawkins"
date: "11/20/2021"
output: html_document
---

```{r}
rm(list = ls())
library(tidyverse)
library(vroom)
library(ggplot2)
library(e1071)
library(randomForest)
library(ranger)
cc <- vroom("CCFraud.csv")
head(cc)

```

# EDA
```{r}
# ggplot(mapping = aes(x = as.factor(Class), y = Amount), data = cc) + 
#   geom_boxplot()
```


# Split Data
```{r}
samp = sample(1:nrow(cc), round(nrow(cc)*0.5))

train = cc[-samp,]
test = cc[samp,]
```


```{r}
K = 10
possibilities = 1:nrow(cc)
this.many = round(nrow(cc)/K)

splits <- list()
already.used <- NA
for(i in 2:K){
  samp <- sample(possibilities, this.many, replace = FALSE)
  splits[[i]] <- samp
  possibilities = possibilities[!(possibilities %in% splits[[i]]) ]
}
splits[[1]] = possibilities
```


# Support Vector Machines
```{r}
library(pROC)
auc_linear = NA
i = 1
for(i in 1:10){
  train = cc[splits[[i]],]
  if(i == 10){
    test = cc[splits[[1]],]
  }
  else{
    test = cc[splits[[i+1]],]
  }
  
  model1 = svm(Class ~ ., data=train, kernel = "linear")
  p1 = predict(model1,newdata = test)
  
  auc_linear[i] = auc(test$Class, p1 )
  
}
mean(auc_linear)


auc_polynomial = NA
i = 1
for(i in 1:10){
  train = cc[splits[[i]],]
  if(i == 10){
    test = cc[splits[[1]],]
  }
  else{
    test = cc[splits[[i+1]],]
  }
  
  model1 = svm(Class ~ ., data=train, kernel = "polynomial")
  p1 = predict(model1,newdata = test)
  
  auc_polynomial[i] = auc(test$Class, p1 )
  preds1 = ifelse(p1 > 0.05, 1, 0)
  
}
mean(auc_polynomial)

auc_radial = NA
i = 1
for(i in 1:10){
  train = cc[splits[[i]],]
  if(i == 10){
    test = cc[splits[[1]],]
  }
  else{
    test = cc[splits[[i+1]],]
  }
  
  model1 = svm(Class ~ ., data=train, kernel = "radial")
  p1 = predict(model1,newdata = test)
  
  auc_radial[i] = auc(test$Class, p1 )

}
mean(auc_radial)


auc_sigmoid = NA
i = 1
for(i in 1:10){
  train = cc[splits[[i]],]
  if(i == 10){
    test = cc[splits[[1]],]
  }
  else{
    test = cc[splits[[i+1]],]
  }
  
  model1 = svm(Class ~ ., data=train, kernel = "sigmoid")
  p1 = predict(model1,newdata = test)
  
  auc_sigmoid[i] = auc(test$Class, p1 )

}

mean(auc_sigmoid)

```


```{r}

model1 = svm(Class ~ ., data=cc, kernel = "sigmoid")

```



```{r}

samp = sample(1:nrow(cc), round(nrow(cc)*0.5))

train = cc[-samp,]
test = cc[samp,]


mylogit <- glm(Class  ~ . , data = train, family = binomial(link = "probit"))
preds <- predict.glm(mylogit, newdata = test)
auc(test$Class, preds)

preds_binary = ifelse(preds > 0.001, 1, 0)
table(preds_binary, test$Class)
table(preds_binary)
```

```{r}
library(pROC)
K = 5
possibilities = 1:nrow(cc)
this.many = round(nrow(cc)/K)

splits <- list()
already.used <- NA
for(i in 2:K){
  samp <- sample(possibilities, this.many, replace = FALSE)
  splits[[i]] <- samp
  possibilities = possibilities[!(possibilities %in% splits[[i]]) ]
}
splits[[1]] = possibilities


auc_logit = NA
for(i in 1:K){
  train = cc[splits[[i]],]
  if(i == K){
    test = cc[splits[[1]],]
  }
  else{
    test = cc[splits[[i+1]],]
  }
  
  mylogit <- glm(Class  ~ . , data = train, family = binomial(link = "logit"))
  p1 = predict(mylogit, newdata = test)
  
  auc_logit[i] = auc(test$Class, p1 )

}
mean(auc_logit)


```


```{r}
cc$Class <- ifelse(cc$Class == 1, "y", "n")
samp = sample(1:nrow(cc), round(nrow(cc)*0.5))

train = cc[-samp,]
test = cc[samp,]
library(caret)
ctrl <- trainControl(method = "cv", 
                     number = 10, 
                     verboseIter = FALSE,
                     sampling = "down", 
                     classProbs = TRUE, 
                     summaryFunction = twoClassSummary)
set.seed(42)

model_rf_under <- train(Class ~ .,
                         data = train,
                         method = "ranger",
                         #preProcess = c("scale", "center"),
                         metric = "ROC",
                         trControl = ctrl)


pred = predict(model_rf_under, newdata = test, type = "prob")
auc(test$Class, pred$y)

table(test$Class, pred$`y`>0.6)

```

# KNN 0.6581
# NN 0.967
# GBM 0.9799
# RF 0.9684
# Ranger 0.984

```{r}
#cc$Class <- ifelse(cc$Class == 1, "y", "n")
samp = sample(1:nrow(cc), round(nrow(cc)*0.5))

train = cc[-samp,]
test = cc[samp,]
library(caret)
ctrl <- trainControl(method = "cv", 
                     number = 10, 
                     verboseIter = FALSE,
                     sampling = "down", 
                     classProbs = TRUE, 
                     summaryFunction = twoClassSummary)
set.seed(42)

model_rf_under <- train(as.factor(Class) ~ .,
                         data = train,
                         method = "ranger",
                         #preProcess = c("scale", "center"),
                         metric = "ROC",
                         trControl = ctrl)


pred = predict(model_rf_under, newdata = test, type = "prob")
auc(test$Class, pred$y)

table(test$Class, pred$`y`>0.6)
```

